services: 
  database: 
    image: mysql:5
    volumes: 
      - ci-cd-volumes:/var/lib/mysql
    environment: 
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    restart: always
    ports:
      - '3303:3306'
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 2
    networks: 
      - ci-cd
  
  backend: 
    image: tommy240302/ci_cd_backend_rua:latest
    ports:
      - "8083:8080"
    environment:
      MYSQL_ROOT: ${MYSQL_ROOT}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_HOST: ${MYSQL_HOST}

    networks: 
      - ci-cd

    depends_on:
      database: 
        condition: service_healthy  

  
  webclient:
    image: tommy240302/ci_cd_frontend_rua:latest
    ports: 
      - '3000:3000'
    environment: 
      - VITE_PORT=3000
    networks: 
      - ci-cd

networks: 
  ci-cd:
  

volumes:
  ci-cd-volumes:




