name: Build ci cd

on:
  push:
    branches:
      - main  # hoặc tên nhánh của bạn

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          java-package: 'jdk'
          architecture: 'x64'
          
      - name: Build Backend
        run: |
          cd backend
          mvn clean package -DskipTests=true
          
      - name: Archive backend artifacts
        uses: actions/upload-artifact@v2
        with:
          name: backend-artifacts
          path: backend/target/*.jar
          
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: tommy240302
          password: Quangdieunghe24
          
      - name: Build and push frontend Docker image
        run: |
          cd ..
          cd frontend
          docker build -t tommy240302/ci_cd_frontend_rua:latest .
          docker push tommy240302/ci_cd_frontend_rua:latest
          
      - name: Build and push backend Docker image
        run: |
          cd backend
          docker build -t tommy240302/ci_cd_backend_rua:latest .
          docker push tommy240302/ci_cd_backend_rua:latest
