name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # or your branch name

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          
      - name: Build with Maven
        run: |
          mvn clean package -DskipTests=true
        # Optionally cache dependencies to speed up builds
        # with:
        #   path: ~/.m2/repository
        #   key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          
      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: backend-artifacts
          path: backend/target/*.jar
          
      - name: Docker Build and Push
        env:
          IMAGE_NAME_BACKEND: username/repository
          IMAGE_TAG: latest
        run: |
          docker build -t $IMAGE_NAME_BACKEND:$IMAGE_TAG .
          docker push $IMAGE_NAME_BACKEND:$IMAGE_TAG
