name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # or your branch name

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          java-package: 'jdk'
          architecture: 'x64'
          check-latest: false
          server-id: 'github'
          server-username: ${{ github.actor }}
          server-password: ${{ github.token }}
          overwrite-settings: true
          job-status: 'success'
          
      - name: Build with Maven
        run: |
          mvn clean package -DskipTests=true
          
      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: backend-artifacts
          path: backend/target/*.jar
          
      - name: Docker Build and Push
        env:
          IMAGE_NAME_BACKEND: username/repository
          IMAGE_TAG: latest
        run: |
          docker build -t $IMAGE_NAME_BACKEND:$IMAGE_TAG .
          docker push $IMAGE_NAME_BACKEND:$IMAGE_TAG
