name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Thay đổi tên branch tại đây nếu cần

jobs:
  maven-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          
      - name: Build backend with Maven
        working-directory: backend
        run: |
          mvn clean package -DskipTests=true
        # Cache Maven dependencies to speed up builds
        # with:
        #   path: ~/.m2/repository
        #   key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        
      - name: Archive backend artifacts
        if: success()
        working-directory: backend
        uses: actions/upload-artifact@v2
        with:
          name: backend-artifacts
          path: target/*.jar

  docker-build:
    runs-on: ubuntu-latest
    needs: maven-build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Login to Docker Hub
        env:
          USERNAME_DOCKER: ${{ secrets.DOCKER_USERNAME }}
          PASSWORD_DOCKER: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo $PASSWORD_DOCKER | docker login -u $USERNAME_DOCKER --password-stdin
        
      - name: Build and push backend Docker image
        working-directory: backend
        env:
          IMAGE_NAME_BACKEND: tommy240302/ci_cd_backend
          IMAGE_TAG_BACKEND: latest
        run: |
          docker build -t $IMAGE_NAME_BACKEND:$IMAGE_TAG_BACKEND .
          docker push $IMAGE_NAME_BACKEND:$IMAGE_TAG_BACKEND
        
      - name: Build and push frontend Docker image
        working-directory: frontend
        env:
          IMAGE_NAME_FRONTEND: tommy240302/ci_cd_frontend
          IMAGE_TAG_FRONTEND: latest
        run: |
          docker build -t $IMAGE_NAME_FRONTEND:$IMAGE_TAG_FRONTEND .
          docker push $IMAGE_NAME_FRONTEND:$IMAGE_TAG_FRONTEND
