name: Build Backend

on:
  push:
    branches:
      - main  # hoặc tên nhánh của bạn

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          java-package: 'jdk'
          architecture: 'x64'
          check-latest: false
          server-id: 'github'
          server-username: ${{ github.actor }}
          server-password: ${{ github.token }}
          overwrite-settings: true
          job-status: 'success'
          
      - name: Build Backend
        run: |
          cd backend
          mvn clean package -DskipTests=true
          
      - name: Archive backend artifacts
        uses: actions/upload-artifact@v2
        with:
          name: backend-artifacts
          path: backend/target/*.jar
          
      - name: Build frontend Docker image
        working-directory: frontend
        env:
          IMAGE_NAME_FRONTEND: username/repository
          IMAGE_TAG: latest
        run: |
          cd ..
          cd frontend
          docker build -t $IMAGE_NAME_FRONTEND:$IMAGE_TAG .
          docker push $IMAGE_NAME_FRONTEND:$IMAGE_TAG
          
      - name: Build backend Docker image
        working-directory: backend
        env:
          IMAGE_NAME_BACKEND: username/repository
          IMAGE_TAG: latest
        run: |
          cd backend
          docker build -t $IMAGE_NAME_BACKEND:$IMAGE_TAG .
          docker push $IMAGE_NAME_BACKEND:$IMAGE_TAG
